### PR TITLE
Add doze to display and Notification Ticker/heads-up disable

### PR DESCRIPTION
**Pull request by xlxfoxxlx**
please refer to https://github.com/AOSP-JF-MM/platform_packages_apps_Settings/pull/3

### CODE REVIEW

**Comment by CheckYourScreen** [comment]
@B--B @smeroni68 did anyone test this out?

**Comment by smeroni68** [comment]
Not yet... some private stuff to follow. But I belive it will be fine mate.

**Comment by CheckYourScreen** [comment]
@xlxfoxxlx you sure we dont need more fixes/commits?
https://github.com/AOSIP/platform_frameworks_base/search?q=ticker&type=Commits&utf8=%E2%9C%93

**Comment by xlxfoxxlx** [comment]
na thats just if we have center clock which we dont as far as i know. the gentle fade one i will probably do still.

**Pull request merged**
