### PR TITLE
Merge Keyguard from AOSP

### LINKED ISSUE #108: Android password protection
Hi,
There is a problem with password protection in ROM , (try submitting bad password five times) it simply does not work at all even though there are sources in aosp for that and it should be working .
Phone mi5 latest stable

### PR DESCRIPTION
**Pull request by Pietia10**
Hello this is a commit that merges keyguard sources from aosp master to rom this should fix https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/108

### CODE REVIEW

**Comment by B--B** [comment]
Hi, I don't think this can be merged for various reasons:
1 This will remove all CAF changes, even harmless changes (and telephony repos must be checked, i honestly don't remember if there are some related changes)
2 Same thing for all the changes we ported, this will nuke all of them (and pretty sure are not related), and will remove all our optimisations
3 ATM with latest sources I can't reproduce the bug you guys were talking about here: https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/108
Tested on Mi5 (encryption + password) and on jf (PIN), every 5 wrong attempts the timeout starts correctly
Swipe not tested yet, but even if it's not working, we should fix it without reverting all the other good things

**Comment by Pietia10** [comment]
I tested on latest stable :^ and it's still there (encryption + pin + fingerprint).

**Comment by smeroni68** [comment]
Can you explain how you tested? Did you swipe 5 times a 6 pin lenght code? Or you tested with shorter swipe codes?

**Comment by Pietia10** [comment]
Oh I tested and it seems to work fine with 6 digit test however when I type
1 -2 digits its not

20.06.2017 4:10 PM "Stefano Meroni" <notifications@github.com> napisał(a):

Can you explain how you tested? Did you swipe 5 times a 6 pin lenght code?
Or you tested with shorter swipe codes?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AOSP-JF-MM/platform_frameworks_base/pull/5#issuecomment-309767298>,
or mute the thread

**Comment by smeroni68** [comment]
Listen: if you are trying to brute force a 6 pin code by swiping only few pins... you are playing with the phone, and you can stay for 2 hours trying to unlock a 6 pin code with 3 or 4 pins.
If you wanna unlock you need 6 pin code... and after 5 trials with wrong 6 pins sequence the phone block with the timer of 30 seconds. Where is the security problem?

**Comment by smeroni68** [comment]
The issue do not exist, security it's fine. Closed.

**Pull request closed without merging**
