### PR TITLE
LEDs, network traffic and some more

### PR DESCRIPTION
**Pull request by xlxfoxxlx**

### CODE REVIEW

**Comment by B--B** [comment]
There's something wrong here, I received a WhatsApp message, turned the screen on and systemui crashes, no way to unlock the phone and catch a log with user build, I will compile a userdebug rom and see if I understand what's wrong with it, do not merge for now :)

**Comment by xlxfoxxlx** [comment]
if you want i can break it up into a couple different pulls to narrow it down. never used WhatsApp so might be a issue here.

**Comment by B--B** [comment]
Some things i forgot to mention in my previous message:
1 Tested on Gemini, jf not tested yet but i suppose this happens on all devices
2 SystemUI crashes during statusbar creation, so i'm pretty sure it's something related to status bar changes
3 I had no time to test network traffic, just played a bit with LED option, reverted to stock values, turned off the screen and then i had the crash (LED works with the right color)
4 The crash MAY be caused by Substratum theme, i will try to reproduce it once i have time, i'm away and i had to revert to latest working version for now, if that is the case then we should fix it in some way, otherwise our user will experience a lot of issues next public release

Theme: SwiftDark

If someone wants to reproduce this:
    * Flash latest public relese
    * Compile ad apply a theme (SwiftDark in my case)
    * Flash latest build (with this and the oher patch in Settings included)
    * Receive a message (in my case a WhatsApp message)
    * Turn on the phone and watch SystemUI that crash recursively

That's all for the moment :)

@xlxfoxxlx No worries, probably i can reproduce it easily with my conf, i just need to compile an userdebug build or reproduce the crash with the phone connected to my PC, should be easy to catch :)

**Comment by xlxfoxxlx** [comment]
sounds good been running a build with all these for past day coming from would be last public release with no issues so far but as i said i never used whatsapp. ill check it out and see if i can reproduce. i did have to delete all overlays and reapply theme after these changes but i believe it was from a settings crash though not sytemui but after that all good.

**Comment by B--B** [comment]
@xlxfoxxlx this makes sense, i had to recompile Settings overlays too because colours were all screwed but i haven't compiled other overlays, if the theme is the root cause of my crash i will merge all this good things, we just need to clean overlays during the flash of next public release, i think we can include in the ROM the zip provided by Substratum guys used for overlays cleaning and execute it like we do with Magisk zip :)

**Comment by CheckYourScreen** [comment]
Working fine here on onyx, Good job  @xlxfoxxlx 👍
Swipe on default keyboard isn't working with opengapps pico though @B--B

**Comment by B--B** [comment]
Well, i was able to reproduce the crash and it's related to Substratum theme, and can be reproduced easily following the steps i previously wrote, this means that we must execute Substratum rescue zip in next public release, otherwise a lot of people with a theme enabled will experience the same crash that happened to me :)

Good work, i will merge this and the companion PR in Settings :)

**Comment by smeroni68** [comment]
Fine guys. ;)

**Comment by CheckYourScreen** [comment]
@B--B Moved our keyboard to aosp-7.1.2-old and replaced it with a fork from lineage with latest caf tag merged.
Swipe gestures were broken on onyx with open pico gapps.

**Comment by B--B** [comment]
@CheckYourScreen No, this will completely break gestures for all devices without Gapps installed, all other devices works fine, please revert that change and add your device here like i did for jf:
https://github.com/AOSP-JF-MM/platform_vendor_aosp/blob/aosp-7.1.2/config/common.mk#L86

Uh i took a look at this too: https://github.com/AOSP-JF-MM/platform_vendor_aosp/commit/915d847bd55920c55ab1af1801b0f6bc278d7c0f Actually it's not causing any issues for me with icon packs, tested with Pixel Icon Pack (Rounded Icons) and MIUI 8 Icon Pack (Square icons with rounded corners), bot of them aplly succesfully and icons are correctly themed

**Comment by CheckYourScreen** [comment]
@B--B why not ship the swipe lib on all devices instead?
Users also reported lags on keyboard so I had to make a change.
https://github.com/AOSP-JF-MM/platform_vendor_aosp/blob/aosp-7.1.2/config/common.mk#L86 This if block wont enable swipe for all other devices so better include the check for arch instead of device/product names and ship the swipe libs in all devices.
Those libs will be replaced by gapps package in case users flash it..

**Comment by CheckYourScreen** [comment]
Let me compile a test build with the new keyboard and test the zip without gapps, since that fall back commit is checking for both libjni_latinime.so and libjni_latinimegoogle.so, there shouldn't be any issue if we ship the libs for all devices according to their arch 🙄 
Opengapps seems to be replacing libjni_latinime with libjni_latinimegoogle so devices need that fallback commit.

**Comment by B--B** [comment]
Check branches differences, only changes are libs recognition and dvorak keyboard fixes, nothing else apart your merge from caf, so it's pretty unuseful, without gapps and with the new branch you won't have the swype option, unless you rename the lib in our vendor repo as jni_latinimegoogle, but you still need to add your device there to the check or change it, I already tried checking the arch but it's breaking arm64 devices

**Comment by CheckYourScreen** [comment]
wait let me make the change to that if block and make it check for Arch instead of device so that it will ship the libjni_latinime to all devices and swipe will work even without gapps on all devices.
Edit: I'll also update the libs from beans gapps package for 7.1.2.

**Comment by B--B** [comment]
You just need to change the check, there's no need to rebase latinime repo which is working fine and has some fixes missing on los

**Comment by CheckYourScreen** [comment]
Let me make the change, you can revert it anytime if it doesn't work for you :)
Since I don't have a arm64 device, you might need to test it, We'll need new keyboard for now with the necessary change to make it work.

**Comment by B--B** [comment]
Nimit there's nothing needed in the branch you pushed, check the code... You basically added a lib check with the fallback that is completely unuseful for us as we ship the lib with swype enabled, and you must rename the lib in our vendor repo otherwise even if the lib has swype capability swype won't work and option will disappear, and you still miss some fixes in the new branch, so I don't understand what is needed in the new branch that is missing in the old...

**Comment by CheckYourScreen** [comment]
Swype was broken for me with open gapps and keyboard lagged for me a lot of time.
I did check the code before pushing the new branch, let me just make the change and push libjni_latinime.so with swype support for both 32 and 64 which will work without gapps too. That check will simply go for libjni_latinimegoogle first, if not found will fallback to our libjni_latinime which already has swipe support so both arm and arm64 devices should have swype irrespective of gapps.
Lets see, if it doesn't work as expected, I'll revert my changes.

**Comment by smeroni68** [comment]
Nimit, we compile both 64 and 32bit (gemini and jflte).

**Comment by B--B** [comment]
That's why I'm saying that it's a nonsense, our prebuilt lib is picked from gapps and it's the same that you find on opengapps packages, so basically you are falling back to the same lib with a different name

**Comment by CheckYourScreen** [comment]
Then why swype didn't work 0.0
Keyboard still lags for me, pop out anim and vibration aren't in sync and gets stuck while typing :/

**Comment by B--B** [comment]
https://github.com/AOSP-JF-MM/platform_packages_inputmethods_LatinIME/commit/555c152a673c20dc315cfbc18f9e30461836d2e3

And due to this if you don't have gapps installed the swype option disappear and swype is unavailable even if libs support gestures

**Comment by CheckYourScreen** [comment]
There's no harm in trying what I want to do, try it once, we can revert the commit easily.
I'm pushing the change in vendor, see if anyone of you can test it on arm64 device plz.

**Comment by CheckYourScreen** [comment]
@B--B @smeroni68 @MZO9400 pushed the change, can anyone of you run a build of arm64 device and see if swype is working without gapps or not?
Edit: @B--B https://github.com/AOSP-JF-MM/platform_vendor_aosp/commit/eb09269309e2ed4b95959f639f191a41e78fb0ce

**Comment by B--B** [comment]
Again, check the code, this will kill swype when gapps are not flashed

https://github.com/AOSP-JF-MM/platform_packages_inputmethods_LatinIME/commit/b83060a840e08d3d80aaff769d7e14a7569a29f0

https://github.com/AOSP-JF-MM/platform_packages_inputmethods_LatinIME/commit/555c152a673c20dc315cfbc18f9e30461836d2e3

https://github.com/AOSP-JF-MM/platform_vendor_aosp/commit/eb09269309e2ed4b95959f639f191a41e78fb0ce

You renamed the lib, if libjni_latinimegoogle.so is not found  swype features will be unavailable 

EDIT: as I previously wrote you just need to change the check in vendor repo

**Comment by CheckYourScreen** [comment]
libs I pushed have swype support, i'll add mHaveGestureLib = true; in second try catch block for libjni_latinime.so  xD
Anyhow, it will remain the same like earlier, but still that keyboard lag is annoying and untraceable :/
I'll revert the changes if you insist so much..

**Comment by B--B** [comment]
The problem is that you added an unuseful check, it's needed only for ROMs thas use stock AOSP libjni_latinime (which is not our case) that does not have swype feature. But our lib have that feature, so you need to revert this https://github.com/AOSP-JF-MM/platform_packages_inputmethods_LatinIME/commit/555c152a673c20dc315cfbc18f9e30461836d2e3 and fake the check, so it should be removed because it's an unuseful operation. You will end with something like this: https://github.com/AOSP-JF-MM/platform_packages_inputmethods_LatinIME/commit/8bd9301ce6834612e4c6882d64436d10d37b850a which is the same thing i already done :) Only thing we miss from the new branch is the CAF merge, that can be merged without any issue :)

Regarding the check on vendor repo i will give it a try, differentiate the libs using arch and not a single device it's absolutely the best thing to do :)

**Comment by CheckYourScreen** [comment]
I rebased the branch and nuked my commit lol
Edit: pushed again, all 32bit devices should be fine now including onyx..

**Comment by B--B** [comment]
Good, i will take a look tomorrow, will compile for both ARCH so we will see if it's working fine :)

**Pull request merged**
